# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'sass', :input => 'scss', :output => 'css'

guard 'livereload' do
  watch(%r{scss/.+\.scss})
  watch(%r{js/.+\.js})
  watch(%r{index.html})
end
